config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'

  resource :registration
  resource :session
  resource :password_reset
  resource :password
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  resources :rooms do
    resources :messages
  end
  resources :users

  resources :active_sessions, only: [:index, :destroy] do
    collection do
      delete "destroy_all"
    end
  end
  root "main#index"
end

app/models/active_session.rb
class ActiveSession < ApplicationRecord
  belongs_to :user
end

app/controllers/active_sessions_controller.rb
class ActiveSessionsController < ApplicationController
    before_action :authenticate_user!

    def index
      @active_sessions = current_user.active_sessions.all
    end
  
    def destroy
      @active_session = current_user.active_sessions.find(params[:id])
  
      @active_session.destroy
  
      if current_user
        redirect_to session_path, notice: "Session deleted."
      else
        reset_session
        redirect_to root_path, notice: "Signed out."
      end
    end
  
    def destroy_all
      current_user.active_sessions.destroy_all
      reset_session
  
      redirect_to root_path, notice: "Signed out."
    end
  end
  

app/helpers/active_sessions_helper.rb
module ActiveSessionsHelper
end

app/views/active_sessions/_active_session.html.erb
<tr>
  <td><%= active_session.user_agent %></td>
  <td><%= active_session.ip_address %></td>
  <td><%= active_session.created_at %></td>
  <td><%= button_to "Sign Out", active_session_path(active_session), method: :delete %></td>
</tr>

app/views/active_sessions/index.html.erb
<%# <%= render partial: "active_session"%> 

<h1>sessions</h1>

<ul>
  <% @active_sessions.each do |active_session| %>

      <tr>
        <b>System details </b>- <td><%= active_session.user_agent %></td> <br>
        <b>ip_address</b>- <td><%= active_session.ip_address %></td><br>
        <b>Login date and time </b>- <td><%= active_session.created_at.in_time_zone('Asia/Kolkata').strftime("%d-%m-%Y %I:%M:%S %p") %></td><br>
        <td><%= button_to "Sign Out", active_session_path(active_session), method: :delete %></td>
    </tr>

  <% end %>
</ul>