config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'

  resource :registration
  resource :session
  resource :password_reset
  resource :password
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  resources :rooms do
    resources :messages
  end
  resources :users

  resources :active_sessions, only: [:index, :destroy] do
    collection do
      delete "destroy_all"
    end
  end
  root "main#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if user_signed_in? %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if current_user.avatar.attached? %>
       <a class="navbar-brand" href="/"> <%= image_tag(current_user.avatar, style: "border-radius: 50%; width: 50px; height: 50px; ") %> </a>
        <% else %>
        <%= link_to "update picture", edit_user_path(current_user) %>
        <% end %>
      </li>
    
      <li class="nav-item">
        <%= link_to "Turbochat", rooms_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Edit Password", edit_password_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "All logged in devices", active_sessions_path, class: "nav-link" %>
      </li>
      <li class="nav-item"> 
        <%= button_to "Log out", session_path, method: :delete, class: "navbar-dark"  %>
      </li>
    </ul>
  </div>
  <% else %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Sign Up", new_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log in", new_session_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
  <% end %>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class:'d-flex',
  data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f| %>
    <div id="attachment-previews"
     class="d-none"
      data-controller="message-preview"
      data-action="message-preview#preview"
      >
    </div>
    <div class="image-upload">
      <label for="message_attachments">
        <i class="bi bi-plus-circle upload-button"></i>
      </label>
      <%= f.file_field(:attachments, multiple: true, 
        data:{controller: "message-preview", action:"change->message-preview#preview"}) %>
    </div>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit "Send",
      data: {disable_with: false, 
      controller: "message-preview", 
      action:"click->message-preview#clearPreviews"}, 
      class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class:'d-flex',
  data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: {disable_with: false} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
        justify-content: flex-end
      }
    </style>
  </head>
  
  <body>
    <%= render "layouts/navbar" %>
    <div><%= notice %> </div>
    <div><%= alert %> </div>

    <%= yield %>
  </body>
</html>